## Vector in maths is a quantities which have dimension and Mangnitude 

## But in Coding/python it is nothing but **collection of numbers in list** 

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [5]:
vector_list = [1,4,7] #in-build python list 

# We create Vector using np.array function of numpy

vector_np_list = np.array([1,4,7])
# np.array expect Either single value called scaler or Python List

print(vector_list)
print(vector_np_list)

[1, 4, 7]
[1 4 7]


## Vector in python have two important characteristics ***1> Dimensionality  <2> Orientation***

In [6]:
# number of numbers in Vector is Dimensionality

print(f"The dimensionality of \"Vector_np_list\" Vector is {len(vector_np_list)}")

The dimensionality of "Vector_np_list" Vector is 3


In [8]:
# Orientation is how is vector represented in space it's either row or column

print(f"The Orientation of \"Vector_np_list\" Vector is {(vector_np_list).shape} ")
# Note :-  this Vector of numpy is actually dimensional-less. 

The Orientation of "Vector_np_list" Vector is (3,) 


In [11]:
rowVector = np.array([[1,4,7]])
columnVector = np.array([[1],[4],[7]])

print(f"Orientation is {rowVector.shape} for a row Vector ")
print(f"Orinetation is {columnVector.shape} for a column Vector")
print(f"We can also have shape of vector as (4,6) which means it's having 4 rows and 6 columns in it.")

Orientation is (1, 3) for a row Vector 
Orinetation is (3, 1) for a column Vector
We can also have shape of vector as (4,6) which means it's having 4 rows and 6 columns in it.


In [13]:
# addition of two vectors

Vector_a = np.array([[1,2,3]])
vector_b = np.array([[1],[2],[3]])

print(Vector_a + vector_b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
